# Generated by Django 3.2.2 on 2021-06-12 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_evaluated', models.DateField(auto_now_add=True, verbose_name='date evaluated')),
                ('remarks', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficiency', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('timeliness', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('quality', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('accuracy', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('performance_average', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='Pending', max_length=20)),
                ('due_date', models.DateField(verbose_name='Date Due')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
