# Generated by Django 3.2.2 on 2021-06-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='assigned to'),
        ),
        migrations.AddField(
            model_name='task',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.evaluator'),
        ),
        migrations.AddField(
            model_name='progress',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.AddField(
            model_name='progress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='evaluator.task'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee', verbose_name='Assigned to'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.evaluator'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='ratings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluator.ratings'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluator.task'),
        ),
    ]
