# Generated by Django 3.2.2 on 2021-06-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='evaluator',
        ),
    ]
