# Generated by Django 3.2.2 on 2021-06-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'pending'), (1, 'in progress'), (2, 'complete')], default='pending', max_length=20),
        ),
    ]
