# Generated by Django 3.2.2 on 2021-06-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('in progress', 'in progress'), ('complete', 'complete')], default='pending', max_length=20),
        ),
    ]
