# Generated by Django 3.2.2 on 2021-06-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0007_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='employee',
        ),
    ]
