# Generated by Django 3.2.2 on 2021-06-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0008_remove_progress_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'created'},
        ),
    ]
