# Generated by Django 3.2.2 on 2021-06-23 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0009_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluation',
            options={'ordering': ['-date_evaluated']},
        ),
        migrations.AlterField(
            model_name='ratings',
            name='performance_average',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
