# Generated by Django 3.2.2 on 2021-06-23 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0010_auto_20210623_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='ratings',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='evaluator.ratings'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='task',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='evaluator.task'),
        ),
    ]
