# Generated by Django 3.2.2 on 2021-06-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='departments',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='designations',
        ),
    ]
